---
baseURL: https://highheathcattery.co.uk/
languageCode: en-us
title: High Heath Farm Cattery
theme: highheath
googleAnalytics: UA-5357036-2
enableRobotsTXT: true
disableKinds:
- taxonomy
- taxonomyTerm
outputs:
  page:
  - HTML
  home:
  - HTML
  section:
  - HTML
markup:
  goldmark:
    parser:
      attribute:
        block: true
params:
  debug: false
menu:
  main:
    - name: Gallery
      url: /accommodation/#gallery
      weight: 3
    - name: Opening Hours
      url: /contact-us/#opening-times
