---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: content/_index.md
  label: Home Page
- type: document
  path: content/accommodation/index.md
  label: Accommodation
- type: document
  path: content/prices.md
  label: Prices
- type: document
  path: content/comments/_index.md
  label: Review Page
  match: "**/*"
- type: document
  path: content/contact-us/_index.md
  label: Contact Us / Opening Times
  match: "**/*"
- type: document
  path: content/book-now/_index.md
  label: Booking Page
  match: "**/*"
- type: document
  path: content/privacy-policy.md
  label: Privacy Policy
- type: document
  path: content/terms-conditions.md
  label: Terms & Conditions
- type: heading
  label: Comments
- type: directory
  path: content/comments
  label: Reviews
  create: all
  match: 20*
- type: heading
  label: Form Redirect Pages
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
