---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: content/_index.md
  label: Home Page
  match: "**/*"
- type: directory
  path: content/accommodation
  label: Accommodation
  create: all
  match: "**/*"
- type: document
  path: content/prices.md
  label: Prices
  match: "**/*"
- type: directory
  path: content/comments
  label: Reviews
  create: all
  match: "**/*"
- type: directory
  path: content/contact-us
  label: Contact us
  create: all
  match: "**/*"
- type: directory
  path: content/book-now
  label: Book now
  create: all
  match: "**/*"
- type: document
  path: content/privacy-policy.md
  label: Privacy Policy
  match: "**/*"
- type: document
  path: content/terms-conditions.md
  label: Terms & Conditions
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
